app/__init__.py
from flask import Flask

import secrets
def create_app():
    
    app = Flask(__name__)

    # Charger la configuration
    app.config.from_pyfile('../config.py')
    
    app.secret_key = secrets.token_hex(16)
    
    from .routes import main
    app.register_blueprint(main)

    return app

app/routes.py
from flask import Blueprint, render_template, request, jsonify, current_app, redirect, url_for,session

import requests

import random
import string
import base64
from .utils import get_access_token, get_artist_top_tracks, get_artists_suggested, get_information_user

# Créer un blueprint
main = Blueprint('main', __name__)

# Route pour la page d'accueil
@main.route('/')
def accueil():
    return render_template('accueil.html')


@main.route('/portfolio')
def portfolio():
    return render_template('portfolio.html')


@main.route('/top_tracks_artist')
def top_tracks_artist():
    return render_template('top_tracks_artist.html')

@main.route('/top_tracks_search')
def top_tracks_search():
    return render_template('top_tracks_search.html')

@main.route('/info_page')
def info_page():
    return render_template('info_page.html')

@main.route('/search')
def search():
    artiste_id = request.args.get('artiste_id')

    client_id = current_app.config.get('SPOTIFY_CLIENT_ID')
    client_secret = current_app.config.get('SPOTIFY_CLIENT_SECRET')

    if not client_id or not client_secret:
        return jsonify({'error': 'Client ID or Secret not configured.'}), 500

    try:
        access_token = get_access_token(client_id, client_secret)
        top_tracks = get_artist_top_tracks(access_token, artiste_id)

        return jsonify({'tracks': top_tracks})

    except Exception as e:
        return jsonify({'error': str(e)})


@main.route('/suggest_artists')
def suggest_artists():
    
    search_name = request.args.get('artiste')
    print('search_name', search_name)
    client_id = current_app.config.get('SPOTIFY_CLIENT_ID')
    client_secret = current_app.config.get('SPOTIFY_CLIENT_SECRET')

    if not client_id or not client_secret:
        return jsonify({'error': 'Client ID or Secret not configured.'}), 500

    try:
        access_token = get_access_token(client_id, client_secret)

        artists_suggested = get_artists_suggested(access_token, search_name)

        if not artists_suggested:
            return jsonify({'error': 'No artists found.'}), 404
        
        artists_suggested = get_artists_suggested(access_token, search_name)

        artists_data = []
        for artist in artists_suggested:
            artist_info = {
                'name': artist['name'],
                'id': artist['id'],
                'image_url': artist['images'][0]['url'] if artist['images'] else ''  # Utiliser la première image si elle existe
            }
            artists_data.append(artist_info)

        return jsonify({'artists_suggested': artists_data})
    

    except Exception as e:
        return jsonify({'error': str(e)}), 500

def generate_random_string(length):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

def get_spotify_auth_url(state):
    return (f"{current_app.config.get('SPOTIFY_AUTH_URL')}?response_type=code&"
            f"client_id={current_app.config.get('SPOTIFY_CLIENT_ID')}&"
            f"redirect_uri={current_app.config.get('SPOTIFY_REDIRECT_URI')}&"
            f"scope={current_app.config.get('SPOTIFY_SCOPES')}&"
            f"state={state}")

@main.route('/login')
def login():
    state = generate_random_string(16)
    session['state'] = state

    print(f"État stocké : {state}")

    return redirect(get_spotify_auth_url(state))

@main.route('/callback')
def callback():
    code = request.args.get('code')
    state = request.args.get('state')
    stored_state = session.get('state')

    print(f"État stocké : {stored_state}")
    print(f"État renvoyé : {state}")

    # if state != session.get('state'):
    #     return "Erreur : état non valide", 400

    auth_header = base64.b64encode(f"{current_app.config.get('SPOTIFY_CLIENT_ID')}:{current_app.config.get('SPOTIFY_CLIENT_SECRET')}".encode()).decode('ascii')
    token_data = {
        'grant_type': 'authorization_code',
        'code': code,
        'redirect_uri': current_app.config.get('SPOTIFY_REDIRECT_URI')
    }

    token_headers = {
        'Authorization': f"Basic {auth_header}",
        'Content-Type': 'application/x-www-form-urlencoded'
    }

    r = requests.post(current_app.config.get('SPOTIFY_TOKEN_URL'), data=token_data, headers=token_headers)
    token_response_data = r.json()

    if r.status_code == 200:
        access_token = token_response_data.get('access_token')
        session['access_token'] = access_token

        return redirect(url_for('main.info_page'))

    else:
        return f"Erreur lors de l'obtention du token : {token_response_data.get('error_description', 'Unknown error')}"
    

@main.route('/api/user_info_tracks', methods=['GET'])
def api_user_info_tracks():
    access_token = session.get('access_token')
    if not access_token:
        return "Utilisateur non authentifié", 401

    headers = {'Authorization': f"Bearer {access_token}"}
    params = {
        'limit': 10,
        'time_range':"short_term",
    }
    r = requests.get(current_app.config.get('SPOTIFY_USER_TOP_TRACKS_URL'), headers=headers, params=params)
    user_data = r.json()

    return user_data["items"]

@main.route('/api/user_info_artists', methods=['GET'])
def api_user_info_artists():
    access_token = session.get('access_token')
    if not access_token:
        return "Utilisateur non authentifié", 401

    headers = {'Authorization': f"Bearer {access_token}"}
    params = {
        'limit': 10,
        'time_range':"short_term",
    }
    r = requests.get(current_app.config.get('SPOTIFY_USER_TOP_ARTISTS_URL'), headers=headers, params=params)
    user_data = r.json()

    return user_data["items"]

app/templates/accueil.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spotistat</title>
    <link rel="icon" href="{{ url_for('static', filename='images/icon_spotistats.png') }}" type="image/png">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/accueil.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet"> <!-- Google Fonts -->

</head>
<body>
    <div class="main-container">
        <div class="nav-bar">
            <div class="logo-spotistat" data-url="{{ url_for('main.accueil') }}">
                <img src="{{ url_for('static', filename='images/logo_spotistats.png') }}" alt="Logo Spotify" id="logo-spotistat">
                <p class="text-spotistat">Spotistat</p>

            </div>
            <div class="search-bar">
                <input class="input" id="search_bar" type="text" placeholder="Rechercher une fonctionnalité...">
            </div>
    
            <div class="about" data-url="{{ url_for('main.portfolio') }}">
                <p>A propos</p>
            </div>
        </div>

        <div class="main-box">
            <div class="feature-box" data-url="{{ url_for('main.top_tracks_artist') }}">
                <div class="feature-logo">
                    <img src="{{ url_for('static', filename='images/icon_top_10.png') }}" alt="Top tracks by artist">
                </div>
                <div class="feature-info">
                    <h3 class="feature-title">Top tracks by artist</h3>
                    <p class="feature-description">Découvrez les meilleures pistes par vos artistes préférés.</p>
                </div>
            </div>
            
            <div class="feature-box" data-url="{{ url_for('main.top_tracks_search') }}">
                <div class="feature-logo">
                    <img src="{{ url_for('static', filename='images/icon_top_tracks_search.png') }}" alt="Top tracks global">
                </div>
                <div class="feature-info">
                    <h3 class="feature-title">Top tracks by search</h3>
                    <p class="feature-description"> Recherchez et explorez les meilleurs morceaux disponibles.</p>
                </div>
            </div>

            <div class="feature-box" data-url="{{ url_for('main.login') }}">
                <div class="feature-logo">
                    <img src="{{ url_for('static', filename='images/icon_me.png') }}" alt="About me">
                </div>
                <div class="feature-info">
                    <h3 class="feature-title">À propos de moi</h3>
                    <p class="feature-description">En savoir plus sur moi et mes artistes préférés.</p>
                </div>
            </div>

            <div class="feature-box" data-url="{{ url_for('main.portfolio') }}">
                <div class="feature-logo">
                    <img src="{{ url_for('static', filename='images/gear_icon.png') }}" alt="zzz">
                </div>
                <div class="feature-info">
                    <h3 class="feature-title">Not Yet Available...</h3>
                    <p class="feature-description">...</p>
                </div>
            </div>
            <div class="feature-box" data-url="{{ url_for('main.portfolio') }}">
                <div class="feature-logo">
                    <img src="{{ url_for('static', filename='images/gear_icon.png') }}" alt="zzz">
                </div>
                <div class="feature-info">
                    <h3 class="feature-title">Not Yet Available...</h3>
                    <p class="feature-description">...</p>
                </div>
            </div>
            <div class="feature-box" data-url="{{ url_for('main.portfolio') }}">
                <div class="feature-logo">
                    <img src="{{ url_for('static', filename='images/gear_icon.png') }}" alt="zzz">
                </div>
                <div class="feature-info">
                    <h3 class="feature-title">Not Yet Available...</h3>
                    <p class="feature-description">...</p>
                </div>
            </div>
            <div class="feature-box" data-url="{{ url_for('main.portfolio') }}">
                <div class="feature-logo">
                    <img src="{{ url_for('static', filename='images/gear_icon.png') }}" alt="zzz">
                </div>
                <div class="feature-info">
                    <h3 class="feature-title">Not Yet Available...</h3>
                    <p class="feature-description">...</p>
                </div>
            </div>
            <div class="feature-box" data-url="{{ url_for('main.portfolio') }}">
                <div class="feature-logo">
                    <img src="{{ url_for('static', filename='images/gear_icon.png') }}" alt="zzz">
                </div>
                <div class="feature-info">
                    <h3 class="feature-title">Not Yet Available...</h3>
                    <p class="feature-description">...</p>
                </div>
            </div>
            <div class="feature-box" data-url="{{ url_for('main.portfolio') }}">
                <div class="feature-logo">
                    <img src="{{ url_for('static', filename='images/gear_icon.png') }}" alt="zzz">
                </div>
                <div class="feature-info">
                    <h3 class="feature-title">Not Yet Available...</h3>
                    <p class="feature-description">...</p>
                </div>
            </div>
            <div class="feature-box" data-url="{{ url_for('main.portfolio') }}">
                <div class="feature-logo">
                    <img src="{{ url_for('static', filename='images/gear_icon.png') }}" alt="zzz">
                </div>
                <div class="feature-info">
                    <h3 class="feature-title">Not Yet Available...</h3>
                    <p class="feature-description">...</p>
                </div>
            </div>
            <div class="feature-box" data-url="{{ url_for('main.portfolio') }}">
                <div class="feature-logo">
                    <img src="{{ url_for('static', filename='images/gear_icon.png') }}" alt="zzz">
                </div>
                <div class="feature-info">
                    <h3 class="feature-title">Not Yet Available...</h3>
                    <p class="feature-description">...</p>
                </div>
            </div>
            <div class="feature-box" data-url="{{ url_for('main.portfolio') }}">
                <div class="feature-logo">
                    <img src="{{ url_for('static', filename='images/gear_icon.png') }}" alt="zzz">
                </div>
                <div class="feature-info">
                    <h3 class="feature-title">Not Yet Available...</h3>
                    <p class="feature-description">...</p>
                </div>
            </div>


        </div>
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>    
    <script src="{{ url_for('static', filename='accueil.js') }}"></script>    
</body>
</html>

app/templates/info_page.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>À propos de moi</title>
    <link rel="icon" href="{{ url_for('static', filename='images/icon_spotistats.png') }}" type="image/png">


    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet"> <!-- Google Fonts -->

    <link rel="stylesheet" href="{{ url_for('static', filename='css/info_page.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>

<body>
    <div class="main-container">
        <div class="nav-bar">
            <div class="logo-spotistat" data-url="{{ url_for('main.accueil') }}">
                <img src="{{ url_for('static', filename='images/logo_spotistats.png') }}" alt="Logo Spotify" id="logo-spotistat">
                <p class="text-spotistat">Spotistat</p>

            </div>
            <div class="search-bar">
                <input class="input" type="text" placeholder="Rechercher une fonctionnalité...">
            </div>
    
            <div class="about">
                <p>A propos</p>
            </div>
        </div>
        

        <div class =choice-container>
            <div class =choice-box>
                <img src="{{ url_for('static', filename='images/icon_tracks.png') }}" alt="icon-tracks-png" class="logo-choices">
                <div class="choice-box-text"> Tracks </div>
            </div>
            <div class =choice-box>
                <img src="{{ url_for('static', filename='images/icon_artists.png') }}" alt="icon-artists-png" class="logo-choices">
                <div class="choice-box-text"> Artists </div>
            </div>
        </div>
        
        <div class="prov">
            Mon TOP 10 (4 semaines)
        </div>

        <div id="results">
            <div id="left-column" class="column"></div>
            <div id="right-column" class="column"></div>
        </div>

    </div>


    <script src="{{ url_for('static', filename='scripts.js') }}"></script>
    <script src="{{ url_for('static', filename='info_page.js') }}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const divTrack = document.querySelector('.choice-container .choice-box:nth-child(1)');
            divTrack.classList.add('selected');
            track_informations();
        });
    </script>
    
</body>
</html>

app/templates/portfolio.html
<!DOCTYPE html>


<html lang="fr">
<head>


</head>


<body>
    <p> :( </p>

</body>


</html>

app/templates/top_tracks_artist.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Top tracks artists</title>
    <link rel="icon" href="{{ url_for('static', filename='images/icon_spotistats.png') }}" type="image/png">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/top_tracks_artist.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet"> <!-- Google Fonts -->

</head>

<body>
    <div class="main-container">
        <div class="nav-bar">
            <div class="logo-spotistat" data-url="{{ url_for('main.accueil') }}">
                <img src="{{ url_for('static', filename='images/logo_spotistats.png') }}" alt="Logo Spotify" id="logo-spotistat">
                <p class="text-spotistat">Spotistat</p>

            </div>
            <div class="search-bar">
                <input class="input" type="text" placeholder="Rechercher une fonctionnalité...">
            </div>
    
            <div class="about">
                <p>A propos</p>
            </div>
        </div>

        <div class="main-div">
            <form id="searchForm">
                <div class="form-group">
                    <input type="text" id="artiste_search_input" name="artiste_search_input" placeholder="Entrez le nom de l'artiste">
                </div>

                <div id="artist-suggestions" class="suggestions-container"></div>

                <button type="button" onclick="searchTopTracks()">Valider</button>
            </form>

            <div id="results"></div>
        </div>
    </div>

    <!-- Lien vers les fichiers JavaScript -->
    <script src="{{ url_for('static', filename='searchTopTracks.js') }}"></script>
    <script src="{{ url_for('static', filename='fetchArtistSuggestions.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>
    
</body>
</html>

app/templates/top_tracks_search.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil</title>
    <link rel="icon" href="{{ url_for('static', filename='images/icon_spotistats.png') }}" type="image/png">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/top_tracks_search.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>

<body>
    <div class="main-container">
        <div class="nav-bar">
            <div class="logo-spotistat" data-url="{{ url_for('main.accueil') }}">
                <img src="{{ url_for('static', filename='images/logo_spotistats.png') }}" alt="Logo Spotify" id="logo-spotistat">
                <p class="text-spotistat">Spotistat</p>

            </div>
            <div class="search-bar">
                <input class="input" type="text" placeholder="Rechercher une fonctionnalité...">
            </div>
    
            <div class="about">
                <p>A propos</p>
            </div>
        </div>
        
        <form id="searchForm">

            <div class="form-group">
                <label for="year">Année :</label>
                <select id="year" name="year">
                    <option value="">Sélectionner une année</option>
                    {% for year in range(2020, 2025) %}
                        <option value="{{ year }}">{{ year }}</option>
                    {% endfor %}
                </select>
            </div>
            
            <div class="form-group">
                <label for="country">Pays :</label>
                <select id="country" name="country">
                    <option value="">Sélectionner un pays</option>
                </select>
            </div>
            
            <div class="form-group">
                <label for="genre">Genre :</label>
                <select id="genre" name="genre">
                    <option value="">Sélectionner un genre</option>
                    <option value="Rap">Rap</option>
                    <option value="Disco">Disco</option>
                    <option value="Techno">Techno</option>
                </select>
            </div>
            
            <div id="artist-suggestions" class="suggestions-container"></div>

            <button type="button" onclick="searchTopTracks()">Valider</button>
        </form>

        <div id="results"></div>
    </div>

    <!-- Lien vers les fichiers JavaScript -->
    <script src="{{ url_for('static', filename='countries.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>

    
</body>
</html>